# Generated by Django 3.2 on 2026-06-16 21:57

import convidados.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convidados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convidados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=convidados.models.foto_upload_path)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.IntegerField()),
                ('endereco', models.CharField(max_length=100)),
                ('complemento', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=50)),
                ('UF', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
            ],
        ),
    ]
