# Generated by Django 3.2 on 2026-06-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convidados', '0002_convidados'),
    ]

    operations = [
        migrations.AddField(
            model_name='convidados',
            name='eventos',
            field=models.ManyToManyField(to='convidados.Eventos'),
        ),
    ]
